###############################################################################
# Smart DNS Server
# BlockList Configuration
###############################################################################

SOCIAL=enabled

ADS=disabled

MALWARE=disabled

ADULTS=disabled

CUSTOM=disabled