###############################################################
# Smart DNS Server
#
# Format:
# Name|Protocol|Primary|Secondary
#
# Protocol:
#   UDP    = Classic DNS
#   DoT    = DNS over TLS
#   DoH    = DNS over HTTPS
#   DoQ    = DNS over QUIC
#
###############################################################

# -------------------------
# Iranian Public DNS
# -------------------------

Shecan|Local|UDP|178.22.122.100|185.51.200.2
Begzar|Local|UDP|185.55.226.26|185.55.225.25
Radar|Local|UDP|10.202.10.10|10.202.10.11
Electro|Local|UDP|78.157.42.100|78.157.42.101
Recursive|Local|UDP|217.218.127.127|217.218.155.155
Pishgaman|Local|UDP|5.202.100.100|5.202.100.101
Shatel|Local|UDP|85.15.1.14|85.15.1.15
Parsonline|Local|UDP|91.239.100.100|89.233.43.71

###############################################################
# End of File
###############################################################